import os

# Define the folder paths to be created.
# This list is generated directly from your provided folder structure.
folder_paths = [
    "apps/web/src/app/(auth)/login", "apps/web/src/app/(auth)/register",
    "apps/web/src/app/(auth)/forgot-password",
    "apps/web/src/app/(dashboard)/dashboard",
    "apps/web/src/app/(dashboard)/repositories",
    "apps/web/src/app/(dashboard)/pull-requests",
    "apps/web/src/app/(dashboard)/reviews",
    "apps/web/src/app/(dashboard)/analytics",
    "apps/web/src/app/(dashboard)/settings", "apps/web/src/app/api/auth",
    "apps/web/src/app/api/webhooks", "apps/web/src/app/api/health",
    "apps/web/src/components/ui/button", "apps/web/src/components/ui/input",
    "apps/web/src/components/ui/modal", "apps/web/src/components/ui/dropdown",
    "apps/web/src/components/ui/toast", "apps/web/src/components/ui/table",
    "apps/web/src/components/ui/badge", "apps/web/src/components/ui/skeleton",
    "apps/web/src/components/forms/auth-forms",
    "apps/web/src/components/forms/repository-forms",
    "apps/web/src/components/forms/settings-forms",
    "apps/web/src/components/layout/header",
    "apps/web/src/components/layout/sidebar",
    "apps/web/src/components/layout/footer",
    "apps/web/src/components/layout/navigation",
    "apps/web/src/components/features/auth",
    "apps/web/src/components/features/dashboard",
    "apps/web/src/components/features/pr-review",
    "apps/web/src/components/features/repository-management",
    "apps/web/src/components/features/analytics",
    "apps/web/src/components/features/billing",
    "apps/web/src/components/providers", "apps/web/src/hooks/api/auth",
    "apps/web/src/hooks/api/repositories",
    "apps/web/src/hooks/api/pull-requests",
    "apps/web/src/hooks/api/ai-reviews", "apps/web/src/hooks/api/analytics",
    "apps/web/src/hooks/api/billing", "apps/web/src/hooks/ui",
    "apps/web/src/hooks/common", "apps/web/src/store/slices",
    "apps/web/src/store/providers", "apps/web/src/services/api/client",
    "apps/web/src/services/api/endpoints", "apps/web/src/services/github",
    "apps/web/src/services/storage", "apps/web/src/services/analytics",
    "apps/web/src/utils/helpers", "apps/web/src/utils/validators",
    "apps/web/src/utils/formatters", "apps/web/src/utils/constants",
    "apps/web/src/types/api", "apps/web/src/types/components",
    "apps/web/src/types/store", "apps/web/src/types/common",
    "apps/web/src/styles", "apps/web/src/lib", "apps/web/tests/__mocks__",
    "apps/web/tests/components", "apps/web/tests/hooks",
    "apps/web/tests/services", "apps/web/tests/utils",
    "apps/web/public/images", "apps/web/public/icons", "apps/web/public/logos",
    "apps/api/src/controllers/auth", "apps/api/src/controllers/repositories",
    "apps/api/src/controllers/pull-requests",
    "apps/api/src/controllers/ai-reviews",
    "apps/api/src/controllers/analytics", "apps/api/src/controllers/billing",
    "apps/api/src/controllers/users", "apps/api/src/controllers/admin",
    "apps/api/src/services/auth", "apps/api/src/services/github",
    "apps/api/src/services/ai", "apps/api/src/services/repository",
    "apps/api/src/services/pull-request", "apps/api/src/services/notification",
    "apps/api/src/services/analytics", "apps/api/src/services/billing",
    "apps/api/src/services/cache", "apps/api/src/services/queue",
    "apps/api/src/repositories/base", "apps/api/src/repositories/auth",
    "apps/api/src/repositories/repository",
    "apps/api/src/repositories/pull-request",
    "apps/api/src/repositories/ai-review",
    "apps/api/src/repositories/analytics", "apps/api/src/repositories/billing",
    "apps/api/src/models/base", "apps/api/src/models/auth",
    "apps/api/src/models/repository", "apps/api/src/models/pull-request",
    "apps/api/src/models/ai-review", "apps/api/src/models/analytics",
    "apps/api/src/models/billing", "apps/api/src/middleware/auth",
    "apps/api/src/middleware/validation", "apps/api/src/middleware/security",
    "apps/api/src/middleware/logging", "apps/api/src/middleware/monitoring",
    "apps/api/src/routes/v1/auth", "apps/api/src/routes/v1/repositories",
    "apps/api/src/routes/v1/pull-requests",
    "apps/api/src/routes/v1/ai-reviews", "apps/api/src/routes/v1/analytics",
    "apps/api/src/routes/v1/billing", "apps/api/src/routes/v1/users",
    "apps/api/src/routes/v1/admin", "apps/api/src/routes/webhooks",
    "apps/api/src/routes/health", "apps/api/src/jobs/ai-review",
    "apps/api/src/jobs/github", "apps/api/src/jobs/notification",
    "apps/api/src/jobs/billing", "apps/api/src/config/database",
    "apps/api/src/config/external-services", "apps/api/src/config/app",
    "apps/api/src/config/auth", "apps/api/src/config/queue",
    "apps/api/src/config/monitoring", "apps/api/src/utils/logger",
    "apps/api/src/utils/encryption", "apps/api/src/utils/validation",
    "apps/api/src/utils/helpers", "apps/api/src/utils/errors",
    "apps/api/src/utils/response", "apps/api/src/types/api",
    "apps/api/src/types/auth", "apps/api/src/types/github",
    "apps/api/src/types/ai", "apps/api/src/types/database",
    "apps/api/src/types/billing", "apps/api/src/types/common",
    "apps/api/src/constants/api", "apps/api/src/constants/auth",
    "apps/api/src/constants/github", "apps/api/src/constants/ai",
    "apps/api/src/constants/billing", "apps/api/src/constants/error",
    "apps/api/src/constants/app", "apps/api/src/enums/auth",
    "apps/api/src/enums/github", "apps/api/src/enums/ai",
    "apps/api/src/enums/billing", "apps/api/src/enums/common",
    "apps/api/src/database/migrations", "apps/api/src/database/seeders",
    "apps/api/src/database/factories", "apps/api/src/database/connection",
    "apps/api/src/events/handlers/github",
    "apps/api/src/events/handlers/billing", "apps/api/src/events/emitters",
    "apps/api/tests/unit/controllers", "apps/api/tests/unit/services",
    "apps/api/tests/unit/repositories", "apps/api/tests/unit/utils",
    "apps/api/tests/unit/middleware", "apps/api/tests/integration/api",
    "apps/api/tests/integration/database",
    "apps/api/tests/integration/external-services",
    "apps/api/tests/integration/webhooks", "apps/api/tests/e2e/auth",
    "apps/api/tests/e2e/repositories", "apps/api/tests/e2e/ai-reviews",
    "apps/api/tests/e2e/billing", "apps/api/tests/fixtures",
    "apps/api/tests/mocks", "apps/api/tests/helpers",
    "packages/shared/src/types/auth", "packages/shared/src/types/github",
    "packages/shared/src/types/ai", "packages/shared/src/types/billing",
    "packages/shared/src/types/api", "packages/shared/src/types/common",
    "packages/shared/src/constants/api", "packages/shared/src/constants/auth",
    "packages/shared/src/constants/github", "packages/shared/src/constants/ai",
    "packages/shared/src/constants/billing",
    "packages/shared/src/constants/error", "packages/shared/src/enums/auth",
    "packages/shared/src/enums/github", "packages/shared/src/enums/ai",
    "packages/shared/src/enums/billing", "packages/shared/src/enums/common",
    "packages/shared/src/utils/validation",
    "packages/shared/src/utils/helpers",
    "packages/shared/src/utils/formatters", "packages/shared/src/schemas/auth",
    "packages/shared/src/schemas/github", "packages/shared/src/schemas/ai",
    "packages/shared/src/schemas/billing", "packages/ui/src/components/atoms",
    "packages/ui/src/components/molecules",
    "packages/ui/src/components/organisms", "packages/ui/src/styles",
    "packages/ui/src/themes", "packages/ui/src/tokens",
    "packages/ui/src/icons", "packages/config/eslint",
    "packages/config/typescript", "packages/config/tailwind",
    "packages/config/prettier", "packages/database/src/schemas",
    "packages/database/src/migrations", "packages/database/src/types",
    "packages/database/src/utils", "packages/ai-engine/src/analyzers",
    "packages/ai-engine/src/generators", "packages/ai-engine/src/models",
    "packages/ai-engine/src/processors", "packages/ai-engine/src/prompts",
    "packages/ai-engine/src/types", "tools/scripts", "tools/generators",
    "tools/migrations", "tools/dev-tools", "infrastructure/docker",
    "infrastructure/k8s", "infrastructure/terraform", "infrastructure/nginx",
    ".github/workflows", ".github/templates", ".github/actions", "tests/e2e",
    "tests/integration", "tests/performance", "docs/api", "docs/architecture",
    "docs/deployment", "docs/user-guides", ".vscode"
]

# Iterate through the list and create each directory
for path in folder_paths:
    os.makedirs(path, exist_ok=True)
    print(f"Created directory: {path}")

print("\nAll folders created successfully!")
